// ZeroToSaaS Accessibility Theme Suite — Tailwind v3 preset.
// Generated by scripts/export-tokens.js — do not edit by hand.
// Usage: module.exports = { presets: [require('./tokens/tailwind.preset.js')] };
// Dark/night variants: switch via [data-z2s-theme*="night"] selector
// (see tokens/zerotosaas.css for the full per-variant override blocks).

/** @type {import('tailwindcss/tailwind-config').Config} */
module.exports = {
  darkMode: ['selector', '[data-z2s-theme*="night"]'],
  theme: {
    extend: {
      colors: {
        z2s: {
                "canvas": "#FCFCFD",
                "fg": "#111827",
                "selection": "#B8D6F8",
                "panic-fg": "#990014",
                "warning-fg": "#8C3800",
                "info-fg": "#0B4F9C",
                "safe-fg": "#0B6229",
                "caution-fg": "#8C3800",
                "focus-border": "#0B4F9C",
                "keywords": "#0B4F9C",
                "functions": "#4F2683",
                "types": "#0B6229",
                "constants": "#784A00",
                "variables": "#111827",
                "comments": "#485260"
        },
      },
    },
  },
};
